version: 2
jobs:
  build:
    working_directory: ~/edx-ora2
    docker:
      - image: circleci/python:2.7.14
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - run:
          command: |
            make install-test
      - run:
          command: |
            make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

